"use client";

import { useSyncExternalStore } from 'react';

type Lang = 'ru' | 'en' | 'kk';

// Подписка на изменения языка
// Подписывает компоненты на смену языка через storage и кастомное событие.
function subscribeToLanguage(onChange: () => void) {
  window.addEventListener('storage', onChange);
  window.addEventListener('language-change', onChange);
  return () => {
    window.removeEventListener('storage', onChange);
    window.removeEventListener('language-change', onChange);
  };
}

// Читает текущий язык из localStorage для useSyncExternalStore.
function getLanguageSnapshot(): Lang {
  const saved = localStorage.getItem('language') as Lang;
  return saved === 'ru' || saved === 'en' || saved === 'kk' ? saved : 'ru';
}

// Сообщает приложению, что язык изменился и компоненты должны обновиться.
function emitLanguageChange() {
  window.dispatchEvent(new Event('language-change'));
}

const translations: Record<Lang, Record<string, string>> = {
  ru: {
    // Footer
    delivery: "Доставка",
    chooseCity: "Выберите город",
    cityNote: "От города зависит срок и стоимость доставки",
    catalog: "Каталог",
    "Электроника": "Электроника",
    "Смартфоны": "Смартфоны",
    "Одежда": "Одежда",
    "Дом": "Дом",
    "Спорт": "Спорт",
    "Авто": "Авто",
    "Книги": "Книги",
    "AI подбор": "AI подбор",
    searchPlaceholder: "Найти товары или спросить ИИ...",
    compare: "Сравнить",
    favorites: "Избранное",
    cart: "Корзина",
    profile: "Профиль",
    guest: "Гость",
    loginOrRegister: "Войдите или создайте аккаунт",
    myProfile: "Мой профиль",
    orderHistory: "Заказы",
    login: "Войти",
    register: "Регистрация",
    language: "Смена языка",
    logout: "Выйти",
    catalogTitle: "Каталог товаров",
    categoryHint: "Выберите категорию для быстрого поиска",
    closeCatalog: "Закрыть каталог",
    allCategories: "Все категории",
    home: "Главная",
    // Footer specific
    footerNav: "Навигация",
    footerContacts: "Контакты",
    footerSettings: "Настройки",
    theme: "Тема",
    marketplaceDescription: "Маркетплейс с ИИ-помощником для быстрого поиска товаров, сравнения и удобных покупок.",
    light: "Светлая",
    dark: "Темная",
    copyright: "© 2026 MarketAI",
    madeFor: "Сделано для удобных покупок",
    catalogLink: "Каталог",
    favoritesLink: "Избранное",
    compareLink: "Сравнение",
    cartLink: "Корзина",
    profileLink: "Профиль",
    agreement: "Соглашение",
    aiAssistant: "AI shopping assistant",
    buyFasterWithAI: "Покупки быстрее с AI-помощником",
    mark: "Марком",
    describeWhatYouNeed: "Опишите, что вам нужно, а Марк подберёт товары, сравнит характеристики и поможет выбрать лучший вариант.",
    askMark: "Спросить Марка",
    goToCatalog: "Перейти в каталог",
    aiPick: "AI подбор",
    whatAreWeLookingFor: "Что ищем сегодня?",
    tryQuery: "Попробуйте запрос: “Найди ноутбук для программирования до 80 000 ₽”",
    smartphoneGoodCamera: "Смартфон с хорошей камерой",
    laptopForStudy: "Ноутбук для учёбы",
    giftUpTo3000: "Подарок до 3000 ₽",
    popularProducts: "Популярные товары",
    popularSubtext: "Подборка товаров с высоким рейтингом и выгодными ценами",
    viewAll: "Смотреть все",
    markGreeting: "Привет, я Марк. Опиши, что хочешь купить, а я подберу подходящие товары.",
    exampleLaptop: "Ноутбук для программирования",
    exampleSmartphone: "Смартфон до 50 000 ₽",
    exampleGift: "Подарок до 3000 ₽",
    inputPlaceholder: "Например: ноутбук для учёбы...",
    send: "Отправить",
    closeAssistant: "Закрыть помощника",
    openAssistant: "Открыть помощника Марка",
    // AuthPage
    marketAIForSellers: "MarketAI для продавцов",
    marketAIAccount: "MarketAI аккаунт",
    createSellerAccount: "Создайте кабинет продавца",
    loginSellerAccount: "Войдите в кабинет продавца",
    createProfile: "Создайте профиль для покупок",
    loginProfile: "Войдите в профиль",
    "errorNameRequired": "Введите имя",
    "errorNameStoreRequired": "Введите название магазина",
    "errorEmailRequired": "Введите email",
    "errorEmailNoCyrillic": "Email не должен содержать кириллицу",
    "errorInvalidEmail": "Введите корректный email",
    "errorPasswordRequired": "Введите пароль",
    "errorPasswordNoCyrillic": "Пароль не должен содержать кириллицу",
    "errorPasswordMinLength": "Пароль должен быть не короче 6 символов",
    "errorConfirmPasswordRequired": "Подтвердите пароль",
    "errorPasswordsDoNotMatch": "Пароли не совпадают",
    "errorAgreementRequired": "Подтвердите пользовательское соглашение",
    "errorInvalidCredentials": "Неверный email или пароль",
    "errorAuthRequestFailed": "Ошибка авторизации",
    "errorEmailVerificationFailed": "Не удалось подтвердить email",
    "errorVerificationCodeRequired": "Введите 6-значный код",
    "errorInvalidVerificationCode": "Неверный код подтверждения",
    "errorResendCodeFailed": "Не удалось отправить код",
    "errorPasswordResetFailed": "Не удалось восстановить пароль",
    "errorStoreNameRequired": "Введите название магазина",
    sellerRegisterDesc: "Зарегистрируйте продавца, чтобы подготовить витрину, карточки товаров и управление заказами.",
    sellerLoginDesc: "Войдите как продавец, чтобы продолжить работу с витриной и заказами.",
    clientRegisterDesc: "Регистрация пока работает на фронтенде: мы сохраним пользователя в состоянии приложения, а бэк подключим позже.",
    clientLoginDesc: "Вход пока без серверной проверки. После отправки формы вы попадете в профиль как авторизованный пользователь.",
    sellerFeatures: "Своя витрина,Карточки товаров,Заказы в работе",
clientFeatures: "Быстрее оформление,Избранное под рукой,История заказов",
    emailVerification: "Подтверждение почты",
    resetPassword: "Восстановление пароля",
    registration: "Регистрация",
    loginForm: "Вход",
    codeSentTo: "Введите код, отправленный на",
    enterEmailToReset: "Введите email аккаунта, чтобы получить код",
    enterSixDigits: "Введите 6 цифр из письма",
    enterNewPassword: "Придумайте новый пароль",
    fillData: "Заполните данные для создания аккаунта",
    enterEmailPassword: "Введите email и пароль от аккаунта",
    forgotPassword: "Забыли пароль?",
    resetPasswordEmailSent: "Код восстановления отправлен на",
    codeConfirmed: "Код подтвержден. Задайте новый пароль.",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердите пароль",
    savePassword: "Сохранить пароль",
    backToLogin: "Вернуться ко входу",
    verificationCode: "Код подтверждения",
    confirmEmail: "Подтвердить email",
    resendCode: "Отправить код еще раз",
    changeData: "Изменить данные",
    storeName: "Название магазина",
    name: "Имя",
    iAccept: "Я принимаю",
    userAgreement: "пользовательское соглашение",
    alreadyHaveAccount: "Уже есть аккаунт?",
    noAccountYet: "Еще нет аккаунта?",
    registerNow: "Зарегистрироваться",
    sellOnMarketAI: "Продавайте на MarketAI",
    // CartPage
    cartTitle: "Корзина",
    cartSubtitle: "Проверьте товары перед оформлением заказа",
    emptyCart: "Корзина пустая",
    emptyCartMessage: "Добавьте товары из каталога, чтобы оформить заказ.",
    deliveryAvailable: "Доставка доступна в выбранный город",
    remove: "Удалить",
    total: "Итого",
    items: "Товары",
    deliveryCost: "Доставка",
    free: "Бесплатно",
    toPay: "К оплате",
    checkout: "Оформить заказ",
    clearCart: "Очистить корзину",
    decreaseQuantity: "Уменьшить количество",
    increaseQuantity: "Увеличить количество",
    // CatalogPage
    catalogPageTitle: "MarketAI catalog",
    catalogTitleDefault: "Каталог товаров",
    "productsInCategory": "Товары из категории",
    "chooseCategoryHint": "Выберите категорию, чтобы перейти к товарам нужного раздела.",
    productsFound: "Найдено:",
    categories: "Категории",
    allProducts: "Все товары",
    nothingFound: "Ничего не найдено",
    tryOtherCategory: "Попробуйте выбрать другую категорию.",
    resetFilters: "Сбросить фильтры",
    // CheckoutPage
    checkoutTitle: "Оформление заказа",
    checkoutSubtitle: "Заполните данные для доставки и выберите способ оплаты",
    backToCart: "Вернуться в корзину",
    recipient: "Получатель",
    recipientDesc: "Контакты для подтверждения заказа",
    address: "Адрес доставки",
    addressDesc: "Курьер привезет заказ по указанному адресу",
    city: "Город",
    street: "Улица",
    house: "Дом",
    apartment: "Квартира",
    comment: "Комментарий",
    commentPlaceholder: "Подъезд, домофон или удобное время доставки",
    deliveryMethod: "Доставка",
    deliveryMethodDesc: "Выберите удобный вариант получения",
    courier: "Курьером",
    courierDesc: "Сегодня, бесплатно",
    pickup: "Самовывоз",
    pickupDesc: "Из пункта выдачи",
    payment: "Оплата",
    paymentDesc: "Сейчас доступна оплата при получении",
    cardOnDelivery: "Картой при получении",
    cardOnDeliveryDesc: "Терминал у курьера",
    cashOnDelivery: "Наличными",
    cashOnDeliveryDesc: "Оплата после проверки",
    yourOrder: "Ваш заказ",
    itemsCount: "товаров",
    confirmOrder: "Подтвердить заказ",
    orderConfirmationNote: "Нажимая кнопку, вы соглашаетесь с условиями обработки заказа.",
    orderPlaced: "Заказ оформлен",
    orderPlacedMessage: "Мы приняли заказ и подготовили его к обработке. Детали отправим на указанные контакты.",
    backToCatalog: "Вернуться в каталог",
    // ComparePage
    compareTitle: "Сравнение товаров",
    compareSubtitle: "Сравните товары по цене, рейтингу и отзывам.",
    added: "Добавлено",
    continueShopping: "Продолжить покупки",
    compareEmpty: "Список сравнения пуст",
    compareEmptyMessage: "Добавьте товары в сравнение, чтобы выбрать лучший вариант.",
    goHome: "На главную",
    product: "Товар",
    rating: "Рейтинг",
    reviewsCount: "отзывов",
    oldPrice: "Старая цена",
    status: "Статус",
    deliveryAvailableShort: "Доступна",
    inCart: "в корзине",
    addToCartShort: "В корзину",
    // FavoritesPage
    favoritesTitle: "Избранное",
    favoritesSubtitle: "Товары, которые вы сохранили для покупки позже",
    favoritesEmpty: "Избранное пустое",
    favoritesEmptyMessage: "Нажмите на сердечко в карточке товара, чтобы сохранить товар здесь.",
    // ProductPage
    homeBreadcrumb: "Главная",
    warranty: "Гарантия",
    months: "месяцев",
    deliveryOption: "Доставка",
    "12months": "12 месяцев",
    "14days": "14 дней",
    todayOrTomorrow: "Сегодня или завтра",
    paymentOption: "Оплата",
    cardOrOnDelivery: "Картой или при получении",
    returnOption: "Возврат",
    days: "дней",
    fastDelivery: "Быстрая доставка",
    officialWarranty: "Официальная гарантия",
    easyReturn: "Удобный возврат",
    aboutProduct: "О товаре",
    specifications: "Характеристики",
    // ProfilePage
    profileTitle: "Профиль",
    profileSubtitle: "Управление аккаунтом и заказами",
    addressTitle: "Адрес доставки",
    addressSubtitle: "Основной адрес пользователя",
    defaultAddress: "г. Екатеринбург, ул. Примерная, д. 10",
    orderHistoryTitle: "История заказов",
    orderHistorySubtitle: "Последние покупки пользователя",
    noOrdersYet: "Сделайте первый заказ",
    noOrdersMessage: "Добавьте товары в корзину и оформите покупку — после этого заказ появится здесь.",
    goToProducts: "Перейти к товарам",
    orderId: "Заказ #",
    itemsCountShort: "товара",
    // AIWidget
    markName: "Марк",
    markSubtitle: "Помогу выбрать товар",
    // ProductCard
    addToCompare: "Добавить в сравнение",
    addToFavorites: "Добавить в избранное",
    inCartShort: "в корзине",
  },
  en: {
    delivery: "Delivery",
    chooseCity: "Choose city",
    cityNote: "Delivery time and cost depend on city",
    catalog: "Catalog",
    searchPlaceholder: "Search products or ask AI...",
    compare: "Compare",
    favorites: "Favorites",
    cart: "Cart",
    profile: "Profile",
    guest: "Guest",
    loginOrRegister: "Login or create account",
    myProfile: "My profile",
    orderHistory: "Orders",
    login: "Login",
    register: "Register",
    language: "Language",
    logout: "Logout",
    catalogTitle: "Product catalog",
    categoryHint: "Select a category for quick search",
    closeCatalog: "Close catalog",
    allCategories: "All categories",
    home: "Home",
    footerNav: "Navigation",
    marketplaceDescription: "Marketplace with AI assistant for quick product search, comparison, and convenient shopping.",
    footerContacts: "Contacts",
    footerSettings: "Settings",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    copyright: "© 2026 MarketAI",
    madeFor: "Made for convenient shopping",
    catalogLink: "Catalog",
    favoritesLink: "Favorites",
    compareLink: "Compare",
    cartLink: "Cart",
    profileLink: "Profile",
    "productsInCategory": "Products in category",
    "chooseCategoryHint": "Select a category to go to the products of the desired section.",
    agreement: "Agreement",
    aiAssistant: "AI shopping assistant",
    buyFasterWithAI: "Shop faster with AI assistant",
    mark: "Mark",
    describeWhatYouNeed: "Describe what you need, and Mark will find products, compare specs, and help you choose the best option.",
    askMark: "Ask Mark",
    goToCatalog: "Go to catalog",
    aiPick: "AI pick",
    whatAreWeLookingFor: "What are we looking for today?",
    tryQuery: "Try query: “Find a laptop for programming under 80,000 RUB”",
    smartphoneGoodCamera: "Smartphone with good camera",
    laptopForStudy: "Laptop for study",
    giftUpTo3000: "Gift under 3000 RUB",
    popularProducts: "Popular products",
    popularSubtext: "Selection of top-rated products with best prices",
    viewAll: "View all",
    markGreeting: "Hi, I'm Mark. Describe what you want to buy, and I'll find suitable products.",
    exampleLaptop: "Laptop for programming",
    exampleSmartphone: "Smartphone under 50,000 RUB",
    exampleGift: "Gift under 3000 RUB",
    inputPlaceholder: "E.g.: laptop for study...",
    send: "Send",
    closeAssistant: "Close assistant",
    "Электроника": "Electronics",
    "Смартфоны": "Smartphones",
    "Одежда": "Clothing",
    "Дом": "Home",
    "Спорт": "Sports",
    "Авто": "Auto",
    "Книги": "Books",
    "AI подбор": "AI pick",
    openAssistant: "Open Mark assistant",
    marketAIForSellers: "MarketAI for sellers",
    marketAIAccount: "MarketAI account",
    createSellerAccount: "Create seller account",
    loginSellerAccount: "Login to seller account",
    createProfile: "Create shopping profile",
    "errorNameRequired": "Name is required",
    "errorNameStoreRequired": "Store name is required",
    "errorEmailRequired": "Email is required",
    "errorEmailNoCyrillic": "Email must not contain Cyrillic",
    "errorInvalidEmail": "Enter a valid email",
    "errorPasswordRequired": "Password is required",
    "errorPasswordNoCyrillic": "Password must not contain Cyrillic",
    "errorPasswordMinLength": "Password must be at least 6 characters",
    "errorConfirmPasswordRequired": "Confirm your password",
    "errorPasswordsDoNotMatch": "Passwords do not match",
    "errorAgreementRequired": "Please accept the user agreement",
    "errorInvalidCredentials": "Invalid email or password",
    "errorAuthRequestFailed": "Authentication failed",
    "errorEmailVerificationFailed": "Failed to verify email",
    "errorVerificationCodeRequired": "Enter the 6-digit code",
    "errorInvalidVerificationCode": "Invalid verification code",
    "errorResendCodeFailed": "Failed to resend the code",
    "errorPasswordResetFailed": "Failed to reset password",
    "errorStoreNameRequired": "Store name is required",
    loginProfile: "Login to profile",
    sellerRegisterDesc: "Register as a seller to set up your storefront, product cards, and order management.",
    sellerLoginDesc: "Login as a seller to continue working with your storefront and orders.",
    clientRegisterDesc: "Registration works on frontend for now: we'll store user in app state, backend will be connected later.",
    clientLoginDesc: "Login is without server validation yet. After submitting the form you'll be redirected to profile as an authorized user.",
    sellerFeatures: "Your storefront,Product cards,Orders in progress",
clientFeatures: "Faster checkout,Favorites at hand,Order history",
    emailVerification: "Email verification",
    resetPassword: "Password reset",
    registration: "Registration",
    loginForm: "Login",
    codeSentTo: "Enter the code sent to",
    enterEmailToReset: "Enter your account email to receive a code",
    enterSixDigits: "Enter the 6-digit code from the email",
    enterNewPassword: "Create a new password",
    fillData: "Fill in the details to create an account",
    enterEmailPassword: "Enter your email and password",
    forgotPassword: "Forgot password?",
    resetPasswordEmailSent: "Recovery code sent to",
    codeConfirmed: "Code confirmed. Set a new password.",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    savePassword: "Save password",
    backToLogin: "Back to login",
    verificationCode: "Verification code",
    confirmEmail: "Confirm email",
    resendCode: "Resend code",
    changeData: "Change data",
    storeName: "Store name",
    name: "Name",
    iAccept: "I accept",
    userAgreement: "user agreement",
    alreadyHaveAccount: "Already have an account?",
    noAccountYet: "No account yet?",
    registerNow: "Register",
    sellOnMarketAI: "Sell on MarketAI",
    cartTitle: "Cart",
    cartSubtitle: "Review your items before checkout",
    emptyCart: "Your cart is empty",
    emptyCartMessage: "Add products from the catalog to place an order.",
    deliveryAvailable: "Delivery available to your city",
    remove: "Remove",
    total: "Total",
    items: "Items",
    deliveryCost: "Delivery",
    free: "Free",
    toPay: "To pay",
    checkout: "Checkout",
    clearCart: "Clear cart",
    decreaseQuantity: "Decrease quantity",
    increaseQuantity: "Increase quantity",
    catalogPageTitle: "MarketAI catalog",
    catalogTitleDefault: "Product catalog",
    productsFound: "Found:",
    categories: "Categories",
    allProducts: "All products",
    nothingFound: "Nothing found",
    tryOtherCategory: "Try another category.",
    resetFilters: "Reset filters",
    checkoutTitle: "Checkout",
    checkoutSubtitle: "Fill in delivery details and choose payment method",
    backToCart: "Back to cart",
    recipient: "Recipient",
    recipientDesc: "Contacts for order confirmation",
    address: "Delivery address",
    addressDesc: "Courier will deliver to this address",
    city: "City",
    street: "Street",
    house: "House",
    apartment: "Apartment",
    comment: "Comment",
    commentPlaceholder: "Entrance, intercom, or convenient delivery time",
    deliveryMethod: "Delivery method",
    deliveryMethodDesc: "Choose convenient delivery option",
    courier: "Courier",
    courierDesc: "Today, free",
    pickup: "Pickup",
    pickupDesc: "From pickup point",
    payment: "Payment",
    paymentDesc: "Payment on delivery available",
    cardOnDelivery: "Card on delivery",
    cardOnDeliveryDesc: "Terminal with courier",
    cashOnDelivery: "Cash",
    cashOnDeliveryDesc: "Pay after inspection",
    yourOrder: "Your order",
    itemsCount: "items",
    confirmOrder: "Confirm order",
    orderConfirmationNote: "By clicking the button you agree to the order processing terms.",
    orderPlaced: "Order placed",
    orderPlacedMessage: "We have received your order and are preparing it for processing. Details will be sent to your contacts.",
    backToCatalog: "Back to catalog",
    compareTitle: "Product comparison",
    compareSubtitle: "Compare products by price, rating, and reviews.",
    added: "Added",
    continueShopping: "Continue shopping",
    compareEmpty: "Comparison list is empty",
    compareEmptyMessage: "Add products to compare to choose the best option.",
    goHome: "Go home",
    product: "Product",
    rating: "Rating",
    reviewsCount: "reviews",
    oldPrice: "Old price",
    status: "Status",
    deliveryAvailableShort: "Available",
    inCart: "in cart",
    addToCartShort: "Add to cart",
    favoritesTitle: "Favorites",
    favoritesSubtitle: "Products you saved for later purchase",
    favoritesEmpty: "Favorites is empty",
    favoritesEmptyMessage: "Tap the heart on a product card to save it here.",
    homeBreadcrumb: "Home",
    warranty: "Warranty",
    months: "months",
    deliveryOption: "Delivery",
    todayOrTomorrow: "Today or tomorrow",
    paymentOption: "Payment",
    cardOrOnDelivery: "Card or on delivery",
    returnOption: "Return",
    days: "days",
    fastDelivery: "Fast delivery",
    officialWarranty: "Official warranty",
    easyReturn: "Easy return",
    aboutProduct: "About product",
    specifications: "Specifications",
    profileTitle: "Profile",
    profileSubtitle: "Manage account and orders",
    addressTitle: "Delivery address",
    addressSubtitle: "Primary user address",
    "12months": "12 months",
    "14days": "14 days",
    defaultAddress: "Ekaterinburg, Example st., 10",
    orderHistoryTitle: "Order history",
    orderHistorySubtitle: "User's recent purchases",
    noOrdersYet: "Make your first order",
    noOrdersMessage: "Add items to cart and checkout — then the order will appear here.",
    goToProducts: "Go to products",
    orderId: "Order #",
    itemsCountShort: "items",
    markName: "Mark",
    markSubtitle: "I'll help you choose",
    addToCompare: "Add to compare",
    addToFavorites: "Add to favorites",
    inCartShort: "in cart",
  },
  kk: {
    delivery: "Жеткізу",
    chooseCity: "Қаланы таңдаңыз",
    cityNote: "Жеткізу мерзімі мен құны қалаға байланысты",
    catalog: "Каталог",
    searchPlaceholder: "Тауарларды іздеу немесе AI сұрау...",
    compare: "Салыстыру",
    favorites: "Таңдаулылар",
    cart: "Себет",
    "errorNameRequired": "Атыңызды енгізіңіз",
    "errorNameStoreRequired": "Дүкен атауын енгізіңіз",
    "errorEmailRequired": "Email енгізіңіз",
    "errorEmailNoCyrillic": "Email кириллицадан тұрмауы керек",
    "errorInvalidEmail": "Дұрыс email енгізіңіз",
    "errorPasswordRequired": "Құпия сөзді енгізіңіз",
    "errorPasswordNoCyrillic": "Құпия сөз кириллицадан тұрмауы керек",
    "errorPasswordMinLength": "Құпия сөз кемінде 6 таңбадан тұруы керек",
    "errorConfirmPasswordRequired": "Құпия сөзді растаңыз",
    "errorPasswordsDoNotMatch": "Құпия сөздер сәйкес келмейді",
    "errorAgreementRequired": "Пайдаланушы келісімін қабылдаңыз",
    "errorInvalidCredentials": "Email немесе құпия сөз қате",
    "errorAuthRequestFailed": "Авторизация сәтсіз аяқталды",
    "errorEmailVerificationFailed": "Email растау сәтсіз аяқталды",
    "errorVerificationCodeRequired": "6 таңбалы кодты енгізіңіз",
    "errorInvalidVerificationCode": "Растау коды қате",
    "errorResendCodeFailed": "Кодты қайта жіберу сәтсіз аяқталды",
    "errorPasswordResetFailed": "Құпия сөзді қалпына келтіру сәтсіз аяқталды",
    "errorStoreNameRequired": "Дүкен атауын енгізіңіз",
    profile: "Профиль",
    "Электроника": "Электроника", 
    "Смартфоны": "Смартфондар",
    "Одежда": "Киім",
    "Дом": "Үй",
    "Спорт": "Спорт",
    "Авто": "Авто",
    "12months": "12 ай",
    "14days": "14 күн",
    "Книги": "Кітаптар",
    "AI подбор": "AI таңдауы",
    guest: "Қонақ",
    loginOrRegister: "Кіру немесе тіркелу",
    myProfile: "Менің профилім",
    orderHistory: "Тапсырыстар",
    login: "Кіру",
    register: "Тіркелу",
    language: "Тіл",
    logout: "Шығу",
    catalogTitle: "Тауарлар каталогы",
    categoryHint: "Жылдам іздеу үшін санатты таңдаңыз",
    closeCatalog: "Каталогты жабу",
    allCategories: "Барлық санаттар",
    home: "Басты бет",
    footerNav: "Навигация",
    footerContacts: "Байланыс",
    footerSettings: "Баптаулар",
    theme: "Тақырып",
    light: "Ашық",
    dark: "Қараңғы",
    copyright: "© 2026 MarketAI",
    madeFor: "Ыңғайлы сатып алу үшін жасалды",
    catalogLink: "Каталог",
    favoritesLink: "Таңдаулылар",
    compareLink: "Салыстыру",
    cartLink: "Себет",
    profileLink: "Профиль",
    agreement: "Келісім",
    aiAssistant: "AI сатып алу көмекшісі",
    buyFasterWithAI: "AI көмекшісімен сатып алу тезірек",
    mark: "Марк",
    describeWhatYouNeed: "Не қажет екенін сипаттаңыз, Марк тауарларды тауып, сипаттамаларды салыстырып, ең жақсы нұсқаны таңдауға көмектеседі.",
    askMark: "Марктан сұрау",
    goToCatalog: "Каталогқа өту",
    aiPick: "AI таңдауы",
    whatAreWeLookingFor: "Бүгін не іздейміз?",
    tryQuery: "Сұраныс үлгісі: “Бағдарламалауға арналған ноутбук 80 000 ₽-ға дейін”",
    smartphoneGoodCamera: "Жақсы камерасы бар смартфон",
    laptopForStudy: "Оқуға арналған ноутбук",
    giftUpTo3000: "3000 ₽-ға дейін сыйлық",
    popularProducts: "Танымал тауарлар",
    popularSubtext: "Жоғары рейтингі және тиімді бағасы бар тауарлар",
    viewAll: "Барлығын көру",
    markGreeting: "Сәлем, мен Марк. Не сатып алғыңыз келетінін жазыңыз, мен сәйкес тауарларды тауып беремін.",
    exampleLaptop: "Бағдарламалауға арналған ноутбук",
    exampleSmartphone: "50 000 ₽-ға дейін смартфон",
    exampleGift: "3000 ₽-ға дейін сыйлық",
    inputPlaceholder: "Мысалы: оқуға арналған ноутбук...",
    send: "Жіберу",
    closeAssistant: "Көмекшіні жабу",
    openAssistant: "Марк көмекшісін ашу",
    marketAIForSellers: "Сатушыларға арналған MarketAI",
    marketAIAccount: "MarketAI аккаунты",
    createSellerAccount: "Сатушы кабинетін құру",
    loginSellerAccount: "Сатушы кабинетіне кіру",
    createProfile: "Сатып алу үшін профиль құру",
    loginProfile: "Профильге кіру",
    sellerRegisterDesc: "Сатушы ретінде тіркеліп, дүкен витринасын, тауар карточкаларын және тапсырыстарды басқаруды дайындаңыз.",
    sellerLoginDesc: "Сатушы ретінде кіріп, витрина және тапсырыстармен жұмысты жалғастырыңыз.",
    clientRegisterDesc: "Тіркелу әзірше фронтендте жұмыс істейді: біз пайдаланушыны қосымша күйінде сақтаймыз, бэкенд кейін қосылады.",
    clientLoginDesc: "Кіру әзірше серверлік тексерусіз. Пішінді жібергеннен кейін профильге авторизацияланған пайдаланушы ретінде өтесіз.",
    sellerFeatures: "Өз витринаң,Тауар карточкалары,Орындалудағы тапсырыстар",
clientFeatures: "Жылдам ресімдеу,Таңдаулылар қол астында,Тапсырыс тарихы",
    emailVerification: "Электрондық поштаны растау",
    resetPassword: "Құпия сөзді қалпына келтіру",
    registration: "Тіркелу",
    loginForm: "Кіру",
    codeSentTo: "Жіберілген кодты енгізіңіз",
    enterEmailToReset: "Код алу үшін аккаунт электрондық поштасын енгізіңіз",
    enterSixDigits: "Хаттан 6 цифрды енгізіңіз",
    enterNewPassword: "Жаңа құпия сөз ойлап табыңыз",
    fillData: "Аккаунт құру үшін деректерді толтырыңыз",
    enterEmailPassword: "Электрондық пошта мен құпия сөзді енгізіңіз",
    forgotPassword: "Құпия сөзді ұмыттыңыз ба?",
    resetPasswordEmailSent: "Қалпына келтіру коды жіберілді",
    codeConfirmed: "Код расталды. Жаңа құпия сөзді орнатыңыз.",
    newPassword: "Жаңа құпия сөз",
    confirmPassword: "Құпия сөзді растаңыз",
    savePassword: "Құпия сөзді сақтау",
    backToLogin: "Кіруге оралу",
    verificationCode: "Растау коды",
    confirmEmail: "Электрондық поштаны растау",
    resendCode: "Кодты қайта жіберу",
    changeData: "Деректерді өзгерту",
    storeName: "Дүкен атауы",
    name: "Аты",
    iAccept: "Мен қабылдаймын",
    userAgreement: "пайдаланушы келісімі",
    alreadyHaveAccount: "Аккаунтыңыз бар ма?",
    noAccountYet: "Аккаунтыңыз жоқ па?",
    registerNow: "Тіркелу",
    sellOnMarketAI: "MarketAI-де сатыңыз",
    cartTitle: "Себет",
    cartSubtitle: "Тапсырыс бермес бұрын тауарларды тексеріңіз",
    emptyCart: "Себет бос",
    emptyCartMessage: "Тапсырыс беру үшін каталогтан тауарларды қосыңыз.",
    deliveryAvailable: "Таңдалған қалаға жеткізу қолжетімді",
    remove: "Жою",
    total: "Барлығы",
    items: "Тауарлар",
    deliveryCost: "Жеткізу",
    free: "Тегін",
    toPay: "Төлеуге",
    checkout: "Тапсырыс беру",
    clearCart: "Себетті тазарту",
    decreaseQuantity: "Санын азайту",
    increaseQuantity: "Санын көбейту",
    catalogPageTitle: "MarketAI каталогы",
    catalogTitleDefault: "Тауарлар каталогы",
    productsFound: "Табылды:",
    categories: "Санаттар",
    allProducts: "Барлық тауарлар",
    nothingFound: "Ештеңе табылмады",
    tryOtherCategory: "Басқа санатты таңдап көріңіз.",
    resetFilters: "Сүзгілерді қалпына келтіру",
    checkoutTitle: "Тапсырысты ресімдеу",
    checkoutSubtitle: "Жеткізу деректерін толтырыңыз және төлем тәсілін таңдаңыз",
    backToCart: "Себетке оралу",
    recipient: "Алушы",
    recipientDesc: "Тапсырысты растау үшін байланыс",
    address: "Жеткізу мекенжайы",
    addressDesc: "Курьер көрсетілген мекенжайға жеткізеді",
    city: "Қала",
    street: "Көше",
    house: "Үй",
    apartment: "Пәтер",
    comment: "Пікір",
    commentPlaceholder: "Кіреберіс, домофон немесе ыңғайлы жеткізу уақыты",
    deliveryMethod: "Жеткізу тәсілі",
    deliveryMethodDesc: "Ыңғайлы жеткізу нұсқасын таңдаңыз",
    courier: "Курьермен",
    courierDesc: "Бүгін, тегін",
    pickup: "Өзіңіз алу",
    pickupDesc: "Беру пунктінен",
    payment: "Төлем",
    paymentDesc: "Қазір қолма-қол төлем қолжетімді",
    cardOnDelivery: "Алғанда картамен",
    cardOnDeliveryDesc: "Курьерде терминал",
    cashOnDelivery: "Қолма-қол",
    cashOnDeliveryDesc: "Тексергеннен кейін төлем",
    yourOrder: "Сіздің тапсырысыңыз",
    itemsCount: "тауар",
    confirmOrder: "Тапсырысты растау",
    orderConfirmationNote: "Түймені басу арқылы сіз тапсырысты өңдеу шарттарымен келісесіз.",
    orderPlaced: "Тапсырыс ресімделді",
    orderPlacedMessage: "Біз тапсырысты қабылдадық және оны өңдеуге дайындап жатырмыз. Деректер сіздің байланыстарыңызға жіберіледі.",
    backToCatalog: "Каталогқа оралу",
    compareTitle: "Тауарларды салыстыру",
    compareSubtitle: "Тауарларды баға, рейтинг және пікірлер бойынша салыстырыңыз.",
    added: "Қосылды",
    continueShopping: "Сатып алуды жалғастыру",
    compareEmpty: "Салыстыру тізімі бос",
    compareEmptyMessage: "Ең жақсы нұсқаны таңдау үшін тауарларды салыстыруға қосыңыз.",
    goHome: "Басты бетке",
    marketplaceDescription: "Тауарларды жылдам іздеу, салыстыру және ыңғайлы сатып алу үшін AI көмекшісі бар маркетплейс.",
    product: "Тауар",
    rating: "Рейтинг",
    reviewsCount: "пікір",
    oldPrice: "Ескі баға",
    status: "Мәртебе",
    "productsInCategory": "Санаттағы тауарлар",
    "chooseCategoryHint": "Қажетті бөлімнің тауарларына өту үшін санатты таңдаңыз.",
    deliveryAvailableShort: "Қолжетімді",
    inCart: "себетте",
    addToCartShort: "Себетке",
    favoritesTitle: "Таңдаулылар",
    favoritesSubtitle: "Кейін сатып алу үшін сақталған тауарлар",
    favoritesEmpty: "Таңдаулылар бос",
    favoritesEmptyMessage: "Тауар карточкасындағы жүрекшеге басып, тауарды осында сақтаңыз.",
    homeBreadcrumb: "Басты бет",
    warranty: "Кепілдік",
    months: "ай",
    deliveryOption: "Жеткізу",
    todayOrTomorrow: "Бүгін немесе ертең",
    paymentOption: "Төлем",
    cardOrOnDelivery: "Картамен немесе алғанда",
    returnOption: "Қайтару",
    days: "күн",
    fastDelivery: "Жылдам жеткізу",
    officialWarranty: "Ресми кепілдік",
    easyReturn: "Ыңғайлы қайтару",
    aboutProduct: "Тауар туралы",
    specifications: "Сипаттамалар",
    profileTitle: "Профиль",
    profileSubtitle: "Аккаунт және тапсырыстарды басқару",
    addressTitle: "Жеткізу мекенжайы",
    addressSubtitle: "Негізгі пайдаланушы мекенжайы",
    defaultAddress: "Екатеринбург қ., Мысалы көш., 10",
    orderHistoryTitle: "Тапсырыс тарихы",
    orderHistorySubtitle: "Пайдаланушының соңғы сатып алулары",
    noOrdersYet: "Алғашқы тапсырысыңызды жасаңыз",
    noOrdersMessage: "Тауарларды себетке қосып, тапсырысты ресімдеңіз — содан кейін ол осында пайда болады.",
    goToProducts: "Тауарларға өту",
    orderId: "Тапсырыс №",
    itemsCountShort: "тауар",
    markName: "Марк",
    markSubtitle: "Тауар таңдауға көмектесемін",
    addToCompare: "Салыстыруға қосу",
    addToFavorites: "Таңдаулыларға қосу",
    inCartShort: "себетте",
  },
};

// Хук возвращает текущий язык, функцию смены языка и переводчик по ключу.
export function useLanguage() {
  const lang = useSyncExternalStore(subscribeToLanguage, getLanguageSnapshot, () => 'ru');

  const changeLanguage = (newLang: string) => {
    if (newLang === 'ru' || newLang === 'en' || newLang === 'kk') {
      localStorage.setItem('language', newLang);
      emitLanguageChange();
    }
  };

// Возвращает перевод по ключу или сам ключ, если перевода нет.
const t = (key: string): string => {
  const selected = translations[lang as keyof typeof translations];
  if (!selected) return key;
  const value = selected[key];
  return value ?? key;
};

  return { lang, changeLanguage, t };
}
