import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import {
  DocumentBuilder,
  type OpenAPIObject,
  SwaggerModule,
} from '@nestjs/swagger';
import cookieParser from 'cookie-parser';
import type { NextFunction, Request, Response } from 'express';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule, { bodyParser: false });
  const logger = new Logger('API Gateway');

  app.use(cookieParser());
  app.use((request: Request, response: Response, next: NextFunction) => {
    const startedAt = Date.now();

    response.on('finish', () => {
      logger.log(
        `${request.method} ${request.originalUrl} ${response.statusCode} ${Date.now() - startedAt}ms`,
      );
    });

    next();
  });

  app.enableCors({
    origin: [
      process.env.CLIENT_URL ?? 'http://127.0.0.1:3000',
      process.env.ADMIN_CLIENT_URL ?? 'http://127.0.0.1:5173',
      process.env.MODERATION_CLIENT_URL ?? 'http://127.0.0.1:5174',
      'http://localhost:3000',
      'http://127.0.0.1:3000',
      'http://localhost:5173',
      'http://127.0.0.1:5173',
      'http://localhost:5174',
      'http://127.0.0.1:5174',
    ],
    credentials: true,
  });

  const swaggerConfig = new DocumentBuilder()
    .setTitle('MarketAI API Gateway')
    .setDescription(
      [
        'Public gateway for MarketAI frontend applications.',
        '',
        'This service authenticates browser requests, applies rate limits and proxies traffic to auth, catalog, cart, order, storage and AI services.',
      ].join('\n'),
    )
    .setVersion('1.0')
    .addServer('http://127.0.0.1:4000', 'Local development')
    .addServer('http://localhost:4000', 'Local development (localhost)')
    .addTag('Auth proxy', 'Routes proxied to auth-service')
    .addTag('Catalog proxy', 'Routes proxied to catalog-service')
    .addTag('Shopping proxy', 'Routes proxied to cart-service')
    .addTag('Order proxy', 'Routes proxied to order-service')
    .addTag('Storage proxy', 'Routes proxied to storage-service')
    .addTag('AI proxy', 'Routes proxied to ai-agent-service')
    .addCookieAuth(
      'accessToken',
      {
        type: 'apiKey',
        in: 'cookie',
        name: 'accessToken',
        description: 'Buyer JWT access token stored in an HttpOnly cookie',
      },
      'accessToken',
    )
    .addCookieAuth(
      'sellerAccessToken',
      {
        type: 'apiKey',
        in: 'cookie',
        name: 'sellerAccessToken',
        description: 'Seller JWT access token stored in an HttpOnly cookie',
      },
      'sellerAccessToken',
    )
    .addApiKey(
      {
        type: 'apiKey',
        in: 'header',
        name: 'x-guest-id',
        description: 'Anonymous AI chat id generated by the client',
      },
      'guestId',
    )
    .build();

  const swaggerDocument = SwaggerModule.createDocument(app, swaggerConfig);
  groupGatewaySwaggerTags(swaggerDocument);

  SwaggerModule.setup('docs', app, swaggerDocument, {
    customSiteTitle: 'MarketAI API Gateway',
    swaggerOptions: {
      docExpansion: 'none',
      filter: true,
      persistAuthorization: true,
      displayRequestDuration: true,
      tagsSorter: 'alpha',
      operationsSorter: 'method',
    },
  });

  await app.listen(process.env.API_GATEWAY_PORT ?? process.env.PORT ?? 4000);
}

function groupGatewaySwaggerTags(document: OpenAPIObject) {
  const tagDescriptions = new Map(
    (document.tags ?? []).map((tag) => [tag.name, tag.description]),
  );

  for (const [path, pathItem] of Object.entries(document.paths)) {
    for (const operation of Object.values(pathItem ?? {})) {
      if (!operation || typeof operation !== 'object' || !('tags' in operation)) {
        continue;
      }

      operation.tags = [getGatewaySwaggerTag(path)];
    }
  }

  document.tags = [
    'Auth proxy',
    'Catalog proxy',
    'Shopping proxy',
    'Order proxy',
    'Storage proxy',
    'AI proxy',
  ].map((name) => ({
    name,
    description: tagDescriptions.get(name),
  }));
}

function getGatewaySwaggerTag(path: string) {
  if (path.startsWith('/api/auth')) return 'Auth proxy';
  if (path.startsWith('/api/catalog')) return 'Catalog proxy';
  if (path.startsWith('/api/cart')) return 'Shopping proxy';
  if (path.startsWith('/api/order') || path.startsWith('/api/orders')) {
    return 'Order proxy';
  }
  if (path.startsWith('/api/storage')) return 'Storage proxy';
  return 'AI proxy';
}

bootstrap();
