import { useState, useEffect, useCallback } from 'react';

type Lang = 'ru' | 'en' | 'kk';

const translations: Record<Lang, Record<string, string>> = {
  ru: {
    // Общие
    "close": "Закрыть",
    "cancel": "Отмена",
    "confirm": "Понятно",
    "save": "Сохранить",
    "add": "Добавить",
    "edit": "Изменить",
    "dashboard": "Обзор",
    "products": "Товары",
    "orders": "Заказы",
    "users": "Пользователи",
    "forSellers": "Продавцам",
    "storeSettings": "Настройки магазина",
    "closeMenu": "Закрыть меню магазина",
    "store": "Магазин",
    "settings": "Настройки",
    "legalData": "Юридические данные",
    "notificationSubscription": "Подписка на уведомления",
    "themeLabel": "Тема",
    "lightTheme": "Светлая",
    "darkTheme": "Тёмная",
    "logout": "Выйти",
    "adminPanel": "Панель администратора",
    "adminSubtitle": "Управление маркетплейсом MarketAI",
    "adminButton": "Администратор",
    "checkFields": "Проверьте поля",
    "checkFieldsMessage": "Заполните название, категорию, цену больше нуля и корректный остаток.",
    "deleteProductTitle": "Удалить товар?",
    "deleteProductMessage": "Товар исчезнет из списка. Это действие нельзя отменить.",
"delete": "Удалить",
    "submit": "Подтвердить",
    "loading": "Загрузка...",
    "back": "Назад",
    // Компоненты
    "editProduct": "Редактировать товар",
    "addProduct": "Добавить товар",
    "productFormNote": "Данные пока сохраняются локально. После готовности backend они будут отправляться через API.",
    "productName": "Название товара",
    "category": "Категория",
    "price": "Цена",
    "stock": "Остаток",
    "status": "Статус",
    "active": "Активный",
    "draft": "Черновик",
    "archived": "Архив",
    "confirmDelete": "Вы уверены?",
    "deleteWarning": "Это действие нельзя отменить.",
    // Dashboard
    "revenue": "Выручка",
    "noDataYet": "Обзор",
    "noDataMessage": "Данных пока нет. Добавьте первый товар или дождитесь первого заказа, чтобы здесь появилась статистика магазина.",
    // Orders
    "manageOrders": "Управление заказами",
    "orderDescription": "Просмотр заказов и изменение статуса обработки.",
    "orderId": "Заказ",
    "customer": "Клиент",
    "amount": "Сумма",
    "orderStatus": "Статус",
    "changeStatus": "Изменить статус",
    "statusNew": "Новый",
    "statusProcessing": "В обработке",
    "statusCompleted": "Завершен",
    "statusCancelled": "Отменен",
    "noOrders": "Заказов пока нет",
    // Products
    "manageProducts": "Управление товарами",
    "productsDescription": "Товары, категории, цены, остатки и статусы публикации.",
    "productListName": "Название",
    "productListCategory": "Категория",
    "productListPrice": "Цена",
    "productListStock": "Остаток",
    "productListStatus": "Статус",
    "actions": "Действия",
    "noProducts": "Товары пока не добавлены",
    // Users
    "manageUsers": "Управление пользователями",
    "usersDescription": "Роли, статусы аккаунтов и доступ к административным функциям.",
    "userName": "Имя",
    "userEmail": "Email",
    "userRole": "Роль",
    "userStatus": "Статус",
    "roleAdmin": "Администратор",
    "roleSeller": "Продавец",
    "roleUser": "Покупатель",
    "statusActive": "Активен",
    "statusBlocked": "Заблокирован",
    "noUsers": "Пользователей пока нет",
    // SellerLoginPage
    "sellersMarketAI": "Продавцы MarketAI",
    "sellerLoginTitle": "Вход в кабинет продавца",
    "errorNameRequired": "Введите имя",
    "errorNameStoreRequired": "Введите название магазина",
    "errorEmailRequired": "Введите email",
    "errorEmailNoCyrillic": "Email не должен содержать кириллицу",
    "errorInvalidEmail": "Введите корректный email",
    "errorPasswordRequired": "Введите пароль",
    "errorPasswordNoCyrillic": "Пароль не должен содержать кириллицу",
    "errorPasswordMinLength": "Пароль должен быть не короче 6 символов",
    "errorConfirmPasswordRequired": "Подтвердите пароль",
    "errorPasswordsDoNotMatch": "Пароли не совпадают",
    "errorAgreementRequired": "Подтвердите пользовательское соглашение",
    "errorInvalidCredentials": "Неверный email или пароль",
    "errorAuthRequestFailed": "Ошибка авторизации",
    "errorEmailVerificationFailed": "Не удалось подтвердить email",
    "errorVerificationCodeRequired": "Введите 6-значный код",
    "errorInvalidVerificationCode": "Неверный код подтверждения",
    "errorResendCodeFailed": "Не удалось отправить код",
    "errorPasswordResetFailed": "Не удалось восстановить пароль",
    "errorStoreNameRequired": "Введите название магазина",
    "sellerLoginDesc": "Продолжайте управлять витриной, карточками товаров и заказами в панели MarketAI.",
    "benefits": "Управление витриной,Обновление остатков,Дашборд заказов",
    "resetPassword": "Восстановление пароля",
    "resetEmailStep": "Введите email аккаунта, чтобы получить код восстановления.",
    "resetCodeStep": "Введите 6 цифр из письма.",
    "resetPasswordStep": "Придумайте новый пароль.",
    "emailPlaceholder": "seller@example.com",
    "codePlaceholder": "000000",
    "sendEmail": "Отправить письмо",
    "confirmCode": "Подтвердить код",
    "saveNewPassword": "Сохранить пароль",
    "backToLogin": "Вернуться ко входу",
    "loginButton": "Войти",
    "noAccountYet": "Еще нет аккаунта продавца?",
    "createAccount": "Создать",
    "forgotPassword": "Забыли пароль?",
    // SellerRegisterPage
    "createSellerAccount": "Создание аккаунта продавца",
    "registerDesc": "Зарегистрируйте магазин, чтобы подготовить товары, управлять заказами и открыть рабочую панель маркетплейса.",
    "registerBenefits": "Настройка витрины,Карточки товаров,Заказы в работе",
    "storeName": "Название магазина",
    "passwordConfirmation": "Подтверждение пароля",
    "acceptAgreement": "Я принимаю пользовательское соглашение",
    "registerButton": "Создать аккаунт продавца",
    "alreadyHaveAccount": "Уже продаёте на MarketAI?",
    "loginLink": "Войти",
    "emailConfirmation": "Подтверждение email",
    "codeSentTo": "Введите код подтверждения, отправленный на",
    "verificationCode": "Код подтверждения",
    "resendCode": "Отправить код ещё раз",
    "changeRegistrationData": "Изменить данные регистрации",
    // SellerWelcomePage
    "sellerCabinet": "Кабинет продавца MarketAI",
    "welcomeTitle": "Запускайте продажи и управляйте магазином в одном месте",
    "welcomeDesc": "Пространство для продавцов: каталог, заказы, пользователи и быстрый обзор состояния магазина без переходов между разными инструментами.",
    "createStore": "Создать магазин",
    "loginCabinet": "Войти в кабинет",
    "workplace": "Рабочая панель",
    "metricsProducts": "Товары",
    "metricsOrders": "Заказы",
    "metricsRevenue": "Выручка",
    "statusOrdersProcessing": "заказов в обработке",
    "statusStockUpdate": "товаров требуют обновления остатков",
    "statusReadyToPublish": "карточки готовы к публикации",
    "highlightStoreControl": "Витрина под контролем",
    "highlightStoreText": "Настраивайте товары, статусы и остатки в одном рабочем пространстве.",
    "highlightOrders": "Заказы без суеты",
    "highlightOrdersText": "Следите за заявками, меняйте статусы и держите операционку рядом.",
    "highlightPulse": "Пульс магазина",
    "highlightPulseText": "Смотрите выручку, активность и ключевые показатели без лишнего шума.",
    // SellerAgreementPage
    "agreementTitle": "Пользовательское соглашение",
    "agreementDesc": "Условия для продавцов, использующих панель MarketAI. Это frontend-версия соглашения, которую можно расширить правилами backend позже.",
    "sectionGeneral": "1. Общие условия",
    "sectionGeneralText": "Соглашение описывает базовые правила использования кабинета продавца MarketAI, включая настройку витрины, управление товарами и обработку заказов.",
    "sectionAccount": "2. Аккаунт продавца",
    "sectionAccountText": "Продавец отвечает за актуальность данных аккаунта, информации о магазине, описаний товаров, цен и сведений по обработке заказов.",
    "sectionProducts": "3. Информация о товарах",
    "sectionProductsText": "Карточки товаров должны содержать корректные названия, категории, цены, остатки и статусы. Демоданные можно заменить после подключения backend-сервисов.",
    "sectionAdmin": "4. Инструменты администрирования",
    "sectionAdminText": "Панель предоставляет интерфейсные инструменты для операций маркетплейса. Бизнес-правила, модерация, платежи и доставка могут быть расширены позже.",
    "sectionUpdates": "5. Обновления",
    "sectionUpdatesText": "MarketAI может обновлять условия по мере развития продукта продавца, добавления backend-сервисов и новых операционных функций.",
    // SellerAuthFooter
    "sellerWorkplace": "Рабочее пространство продавца для витрины, каталога и обработки заказов.",
    "sellerNavigation": "Навигация",
    "sellerContacts": "Контакты",
    "sellerSettings": "Настройки",
    "sellerTheme": "Тема",
    "sellerLanguage": "Язык",
    "sellerFooterCopyright": "© 2026 MarketAI",
    "sellerFooterTagline": "Инструменты продавца для управления маркетплейсом",
    "settingsEyebrow": "Настройки магазина",
    "settingsTitle": "Профиль, доступы и безопасность",
    "settingsDescription": "Управляйте данными магазина, юридической информацией, ролями команды и критичными действиями.",
    "settingsSave": "Сохранить",
    "settingsSaved": "Настройки сохранены локально.",
    "settingsStore": "Магазин",
    "settingsStoreDescription": "Обложка, название, описание и контакты, которые помогают покупателям узнать продавца.",
    "settingsCover": "Обложка",
    "settingsCoverHint": "Загрузите изображение обложки вручную",
    "settingsCoverUpload": "Добавить обложку",
    "settingsStoreName": "Название магазина",
    "settingsStoreNamePlaceholder": "Название магазина",
    "settingsStoreDescriptionField": "Описание",
    "settingsStoreDescriptionPlaceholder": "Расскажите, что продает магазин и чем он полезен покупателям.",
    "settingsCity": "Город",
    "settingsCityPlaceholder": "Екатеринбург",
    "settingsPhone": "Телефон",
    "settingsEmail": "Почта",
    "settingsLegal": "Юридические данные",
    "settingsLegalDescription": "Данные для проверки продавца, документов и выплат.",
    "settingsLegalSave": "Сохранить юр. данные",
    "settingsLegalSubmit": "Отправить на проверку",
    "settingsLegalSaved": "Юридические данные сохранены.",
    "settingsLegalSubmitted": "Юридические данные отправлены на проверку.",
    "settingsBusinessType": "Тип продавца",
    "settingsBusinessIndividual": "ИП",
    "settingsBusinessCompany": "ТОО / компания",
    "settingsBusinessSelfEmployed": "Самозанятый",
    "settingsTaxId": "ИИН / БИН",
    "settingsLegalName": "Юридическое название",
    "settingsLegalNamePlaceholder": "ИП MarketAI Store",
    "settingsLegalAddress": "Юридический адрес",
    "settingsLegalAddressPlaceholder": "Город, улица, дом",
    "settingsBankName": "Банк",
    "settingsBankNamePlaceholder": "Название банка",
    "settingsIban": "IBAN / счет",
    "settingsTeam": "Команда и доступы",
    "settingsTeamDescription": "Приглашайте сотрудников и назначайте роли для работы с заказами, товарами и аналитикой.",
    "settingsTeamLocked": "Команда и доступы станут доступны после активации магазина.",
    "settingsTeamEmailPlaceholder": "email сотрудника",
    "settingsInvite": "Пригласить",
    "settingsInviteTitle": "Пригласить участника",
    "settingsInviteDescription": "Заполните данные сотрудника и выберите роль доступа.",
    "settingsInviteSubmit": "Отправить приглашение",
    "settingsMemberName": "Имя",
    "settingsMemberNamePlaceholder": "Имя сотрудника",
    "settingsRole": "Роль",
    "settingsRoleOwner": "Владелец",
    "settingsRoleManager": "Менеджер",
    "settingsRoleOperator": "Оператор заказов",
    "settingsRoleViewer": "Просмотр",
    "settingsTeamActive": "Активен",
    "settingsTeamInvited": "Приглашен",
    "settingsDanger": "Опасная зона",
    "settingsDangerDescription": "Действия, которые влияют на доступность магазина и данные продавца.",
    "settingsDeactivateTitle": "Поставить магазин на паузу",
    "settingsDeactivateDescription": "Покупатели временно не смогут оформить новые заказы.",
    "settingsDeactivate": "Поставить на паузу",
    "settingsDeactivateDialog": "Это действие пока подготовлено как frontend-сценарий. После подключения backend оно будет менять статус магазина.",
    "settingsDeleteTitle": "Удалить магазин",
    "settingsDeleteDescription": "Удаление магазина потребует дополнительного подтверждения и проверки прав владельца.",
    "settingsDelete": "Удалить магазин",
    "settingsDeleteDialog": "Удаление магазина пока не выполняется без backend-подтверждения. Действие оставлено как защищенная точка интерфейса.",
    "sellerStatusPendingLegal": "Заполните юридические данные, чтобы отправить магазин на проверку.",
    "sellerStatusUnderReview": "На проверке",
    "sellerStatusRejected": "Нужно исправить юридические данные",
    "sellerStatusSuspended": "Магазин заблокирован",
    "moderationMenu": "Модерация",
    "moderationTitle": "Модерация продавцов",
    "moderationDescription": "Проверяйте юридические данные продавцов и одобряйте или отклоняйте заявки.",
    "moderationKey": "Ключ модерации",
    "moderationKeyRequired": "Введите MODERATION_ADMIN_KEY.",
    "moderationLoad": "Загрузить заявки",
    "moderationRefresh": "Обновить",
    "moderationLoadFailed": "Не удалось загрузить заявки.",
    "moderationActionFailed": "Не удалось выполнить действие.",
    "moderationEmpty": "Заявок на проверку пока нет.",
    "moderationApprove": "Одобрить",
    "moderationReject": "Отклонить",
    "moderationApproved": "Одобрено:",
    "moderationRejected": "Отклонено:",
    "moderationSubmittedAt": "Отправлено",
    "moderationRejectTitle": "Отклонить заявку",
    "moderationRejectComment": "Комментарий для продавца",
    "moderationRejectPlaceholder": "Например: исправьте ИИН/БИН и юридический адрес",
    "moderationRejectCommentRequired": "Добавьте комментарий с причиной отклонения.",
  },
  en: {
    "close": "Close",
    "cancel": "Cancel",
    "confirm": "OK",
    "save": "Save",
    "add": "Add",
    "edit": "Edit",
    "dashboard": "Dashboard",
    "products": "Products",
    "orders": "Orders",
    "users": "Users",
    "forSellers": "For Sellers",
    "storeSettings": "Store settings",
    "closeMenu": "Close store menu",
    "store": "Store",
    "settings": "Settings",
    "legalData": "Legal information",
    "notificationSubscription": "Notification subscription",
    "themeLabel": "Theme",
    "lightTheme": "Light",
    "darkTheme": "Dark",
    "logout": "Log out",
    "adminPanel": "Admin panel",
    "adminSubtitle": "MarketAI marketplace management",
    "adminButton": "Admin",
    "checkFields": "Check fields",
    "checkFieldsMessage": "Please fill in name, category, price greater than zero and valid stock.",
    "deleteProductTitle": "Delete product?",
    "deleteProductMessage": "The product will be removed from the list. This action cannot be undone.",
    "delete": "Delete",
    "submit": "Submit",
    "loading": "Loading...",
    "back": "Back",
    "editProduct": "Edit product",
    "addProduct": "Add product",
    "productFormNote": "Data is currently saved locally. After backend is ready, it will be sent via API.",
    "productName": "Product name",
    "category": "Category",
    "price": "Price",
    "stock": "Stock",
    "status": "Status",
    "active": "Active",
    "draft": "Draft",
    "archived": "Archived",
    "confirmDelete": "Are you sure?",
    "deleteWarning": "This action cannot be undone.",
    "revenue": "Revenue",
    "noDataYet": "Overview",
    "noDataMessage": "No data yet. Add your first product or wait for the first order to see store statistics here.",
    "manageOrders": "Manage orders",
    "orderDescription": "View orders and change processing status.",
    "orderId": "Order",
    "customer": "Customer",
    "amount": "Amount",
    "orderStatus": "Status",
    "changeStatus": "Change status",
    "statusNew": "New",
    "statusProcessing": "Processing",
    "statusCompleted": "Completed",
    "statusCancelled": "Cancelled",
    "noOrders": "No orders yet",
    "errorNameRequired": "Name is required",
    "errorNameStoreRequired": "Store name is required",
    "errorEmailRequired": "Email is required",
    "errorEmailNoCyrillic": "Email must not contain Cyrillic",
    "errorInvalidEmail": "Enter a valid email",
    "errorPasswordRequired": "Password is required",
    "errorPasswordNoCyrillic": "Password must not contain Cyrillic",
    "errorPasswordMinLength": "Password must be at least 6 characters",
    "errorConfirmPasswordRequired": "Confirm your password",
    "errorPasswordsDoNotMatch": "Passwords do not match",
    "errorAgreementRequired": "Please accept the user agreement",
    "errorInvalidCredentials": "Invalid email or password",
    "errorAuthRequestFailed": "Authentication failed",
    "errorEmailVerificationFailed": "Failed to verify email",
    "errorVerificationCodeRequired": "Enter the 6-digit code",
    "errorInvalidVerificationCode": "Invalid verification code",
    "errorResendCodeFailed": "Failed to resend the code",
    "errorPasswordResetFailed": "Failed to reset password",
    "errorStoreNameRequired": "Store name is required",
    "manageProducts": "Manage products",
    "productsDescription": "Products, categories, prices, stock and publication statuses.",
    "productListName": "Name",
    "productListCategory": "Category",
    "productListPrice": "Price",
    "productListStock": "Stock",
    "productListStatus": "Status",
    "actions": "Actions",
    "noProducts": "No products added yet",
    "manageUsers": "Manage users",
    "usersDescription": "Roles, account statuses and access to administrative functions.",
    "userName": "Name",
    "userEmail": "Email",
    "userRole": "Role",
    "userStatus": "Status",
    "roleAdmin": "Admin",
    "roleSeller": "Seller",
    "roleUser": "Customer",
    "statusActive": "Active",
    "statusBlocked": "Blocked",
    "noUsers": "No users yet",
    "sellersMarketAI": "MarketAI for sellers",
    "sellerLoginTitle": "Seller login",
    "sellerLoginDesc": "Continue managing your storefront, product cards and orders in the MarketAI panel.",
    "benefits": "Storefront management,Stock updates,Order dashboard",
    "resetPassword": "Password reset",
    "resetEmailStep": "Enter your account email to receive a recovery code.",
    "resetCodeStep": "Enter the 6-digit code from the email.",
    "resetPasswordStep": "Create a new password.",
    "emailPlaceholder": "seller@example.com",
    "codePlaceholder": "000000",
    "sendEmail": "Send email",
    "confirmCode": "Confirm code",
    "saveNewPassword": "Save password",
    "backToLogin": "Back to login",
    "loginButton": "Log in",
    "noAccountYet": "Don't have a seller account?",
    "createAccount": "Create",
    "forgotPassword": "Forgot password?",
    "createSellerAccount": "Create seller account",
    "registerDesc": "Register your store to prepare products, manage orders and open the marketplace dashboard.",
    "registerBenefits": "Storefront setup,Product cards,Orders in progress",
    "storeName": "Store name",
    "passwordConfirmation": "Confirm password",
    "acceptAgreement": "I accept the user agreement",
    "registerButton": "Create seller account",
    "alreadyHaveAccount": "Already selling on MarketAI?",
    "loginLink": "Log in",
    "emailConfirmation": "Email confirmation",
    "codeSentTo": "Enter the verification code sent to",
    "verificationCode": "Verification code",
    "resendCode": "Resend code",
    "changeRegistrationData": "Change registration data",
    "sellerCabinet": "MarketAI Seller Cabinet",
    "welcomeTitle": "Launch sales and manage your store in one place",
    "welcomeDesc": "A space for sellers: catalog, orders, users and a quick store overview without switching between different tools.",
    "createStore": "Create store",
    "loginCabinet": "Log in",
    "workplace": "Dashboard",
    "metricsProducts": "Products",
    "metricsOrders": "Orders",
    "metricsRevenue": "Revenue",
    "statusOrdersProcessing": "orders in processing",
    "statusStockUpdate": "products need stock update",
    "statusReadyToPublish": "cards ready to publish",
    "highlightStoreControl": "Storefront under control",
    "highlightStoreText": "Manage products, statuses and stock in one workspace.",
    "highlightOrders": "Hassle-free orders",
    "highlightOrdersText": "Track requests, change statuses and keep operations close.",
    "highlightPulse": "Store pulse",
    "highlightPulseText": "See revenue, activity and key metrics without noise.",
    "agreementTitle": "User agreement",
    "agreementDesc": "Terms for sellers using the MarketAI panel. This is a frontend version of the agreement that can be extended with backend rules later.",
    "sectionGeneral": "1. General terms",
    "sectionGeneralText": "The agreement describes the basic rules for using the MarketAI seller cabinet, including storefront setup, product management and order processing.",
    "sectionAccount": "2. Seller account",
    "sectionAccountText": "The seller is responsible for the accuracy of account data, store information, product descriptions, prices and order processing information.",
    "sectionProducts": "3. Product information",
    "sectionProductsText": "Product cards must contain correct names, categories, prices, stock and statuses. Demo data can be replaced after backend services are connected.",
    "sectionAdmin": "4. Administration tools",
    "sectionAdminText": "The panel provides interface tools for marketplace operations. Business rules, moderation, payments and delivery may be extended later.",
    "sectionUpdates": "5. Updates",
    "sectionUpdatesText": "MarketAI may update the terms as the seller product evolves, backend services are added and new operational functions appear.",
    "sellerWorkplace": "Seller workspace for storefront, catalog and order management.",
    "sellerNavigation": "Navigation",
    "sellerContacts": "Contacts",
    "sellerSettings": "Settings",
    "Активный": "Active",
    "Черновик": "Draft",
    "Архив": "Archived",
    "sellerTheme": "Theme",
    "sellerLanguage": "Language",
    "sellerFooterCopyright": "© 2026 MarketAI",
    "sellerFooterTagline": "Seller tools for marketplace management",
    "settingsEyebrow": "Store settings",
    "settingsTitle": "Profile, access and safety",
    "settingsDescription": "Manage store details, legal information, team roles and critical actions.",
    "settingsSave": "Save",
    "settingsSaved": "Settings saved locally.",
    "settingsStore": "Store",
    "settingsStoreDescription": "Cover, name, description and contacts that help buyers recognize the seller.",
    "settingsCover": "Cover",
    "settingsCoverHint": "Upload a cover image manually",
    "settingsCoverUpload": "Add cover",
    "settingsStoreName": "Store name",
    "settingsStoreNamePlaceholder": "Store name",
    "settingsStoreDescriptionField": "Description",
    "settingsStoreDescriptionPlaceholder": "Tell buyers what the store sells and why it is useful.",
    "settingsCity": "City",
    "settingsCityPlaceholder": "Yekaterinburg",
    "settingsPhone": "Phone",
    "settingsEmail": "Email",
    "settingsLegal": "Legal data",
    "settingsLegalDescription": "Data for seller verification, documents and payouts.",
    "settingsLegalSave": "Save legal data",
    "settingsLegalSubmit": "Submit for review",
    "settingsLegalSaved": "Legal data saved.",
    "settingsLegalSubmitted": "Legal data submitted for review.",
    "settingsBusinessType": "Seller type",
    "settingsBusinessIndividual": "Individual entrepreneur",
    "settingsBusinessCompany": "Company",
    "settingsBusinessSelfEmployed": "Self-employed",
    "settingsTaxId": "Tax ID",
    "settingsLegalName": "Legal name",
    "settingsLegalNamePlaceholder": "MarketAI Store",
    "settingsLegalAddress": "Legal address",
    "settingsLegalAddressPlaceholder": "City, street, building",
    "settingsBankName": "Bank",
    "settingsBankNamePlaceholder": "Bank name",
    "settingsIban": "IBAN / account",
    "settingsTeam": "Team and access",
    "settingsTeamDescription": "Invite teammates and assign roles for orders, products and analytics.",
    "settingsTeamLocked": "Team and access will become available after store activation.",
    "settingsTeamEmailPlaceholder": "teammate email",
    "settingsInvite": "Invite",
    "settingsInviteTitle": "Invite teammate",
    "settingsInviteDescription": "Fill in the teammate details and choose their access role.",
    "settingsInviteSubmit": "Send invite",
    "settingsMemberName": "Name",
    "settingsMemberNamePlaceholder": "Teammate name",
    "settingsRole": "Role",
    "settingsRoleOwner": "Owner",
    "settingsRoleManager": "Manager",
    "settingsRoleOperator": "Order operator",
    "settingsRoleViewer": "Viewer",
    "settingsTeamActive": "Active",
    "settingsTeamInvited": "Invited",
    "settingsDanger": "Danger zone",
    "settingsDangerDescription": "Actions that affect store availability and seller data.",
    "settingsDeactivateTitle": "Pause the store",
    "settingsDeactivateDescription": "Buyers will temporarily be unable to place new orders.",
    "settingsDeactivate": "Pause store",
    "settingsDeactivateDialog": "This action is currently prepared as a frontend flow. After backend connection it will change the store status.",
    "settingsDeleteTitle": "Delete store",
    "settingsDeleteDescription": "Store deletion will require additional confirmation and owner permission checks.",
    "settingsDelete": "Delete store",
    "settingsDeleteDialog": "Store deletion is not performed without backend confirmation yet. The action is left as a protected interface point.",
    "sellerStatusPendingLegal": "Fill in legal data to submit the store for review.",
    "sellerStatusUnderReview": "Under review",
    "sellerStatusRejected": "Legal data needs corrections",
    "sellerStatusSuspended": "Store is suspended",
    "moderationMenu": "Moderation",
    "moderationTitle": "Seller moderation",
    "moderationDescription": "Review seller legal data and approve or reject applications.",
    "moderationKey": "Moderation key",
    "moderationKeyRequired": "Enter MODERATION_ADMIN_KEY.",
    "moderationLoad": "Load applications",
    "moderationRefresh": "Refresh",
    "moderationLoadFailed": "Failed to load applications.",
    "moderationActionFailed": "Failed to perform action.",
    "moderationEmpty": "No applications are waiting for review.",
    "moderationApprove": "Approve",
    "moderationReject": "Reject",
    "moderationApproved": "Approved:",
    "moderationRejected": "Rejected:",
    "moderationSubmittedAt": "Submitted",
    "moderationRejectTitle": "Reject application",
    "moderationRejectComment": "Comment for seller",
    "moderationRejectPlaceholder": "For example: fix tax ID and legal address",
    "moderationRejectCommentRequired": "Add a comment with rejection reason.",
  },
  kk: {
    "close": "Жабу",
    "cancel": "Болдырмау",
    "confirm": "Түсінікті",
    "save": "Сақтау",
    "add": "Қосу",
    "edit": "Өзгерту",
    "delete": "Жою",
    "submit": "Растау",
    "loading": "Жүктелуде...",
    "back": "Артқа",
    "editProduct": "Тауарды өңдеу",
    "addProduct": "Тауар қосу",
    "productFormNote": "Деректер әзірше жергілікті түрде сақталады. Backend дайын болғаннан кейін олар API арқылы жіберіледі.",
    "productName": "Тауар атауы",
    "category": "Санат",
    "price": "Бағасы",
    "stock": "Қалдық",
    "status": "Мәртебе",
    "dashboard": "Бақылау панелі",
    "products": "Тауарлар",
    "orders": "Тапсырыстар",
    "users": "Пайдаланушылар",
    "forSellers": "Сатушыларға",
    "storeSettings": "Дүкен баптаулары",
    "closeMenu": "Дүкен мәзірін жабу",
    "store": "Дүкен",
    "settings": "Баптаулар",
    "legalData": "Заңды деректер",
    "notificationSubscription": "Хабарландыруларға жазылу",
    "themeLabel": "Тақырып",
    "lightTheme": "Ашық",
    "darkTheme": "Қараңғы",
    "logout": "Шығу",
    "errorNameRequired": "Атыңызды енгізіңіз",
    "errorNameStoreRequired": "Дүкен атауын енгізіңіз",
    "errorEmailRequired": "Email енгізіңіз",
    "errorEmailNoCyrillic": "Email кириллицадан тұрмауы керек",
    "errorInvalidEmail": "Дұрыс email енгізіңіз",
    "errorPasswordRequired": "Құпия сөзді енгізіңіз",
    "errorPasswordNoCyrillic": "Құпия сөз кириллицадан тұрмауы керек",
    "errorPasswordMinLength": "Құпия сөз кемінде 6 таңбадан тұруы керек",
    "errorConfirmPasswordRequired": "Құпия сөзді растаңыз",
    "errorPasswordsDoNotMatch": "Құпия сөздер сәйкес келмейді",
    "errorAgreementRequired": "Пайдаланушы келісімін қабылдаңыз",
    "errorInvalidCredentials": "Email немесе құпия сөз қате",
    "errorAuthRequestFailed": "Авторизация сәтсіз аяқталды",
    "errorEmailVerificationFailed": "Email растау сәтсіз аяқталды",
    "errorVerificationCodeRequired": "6 таңбалы кодты енгізіңіз",
    "errorInvalidVerificationCode": "Растау коды қате",
    "errorResendCodeFailed": "Кодты қайта жіберу сәтсіз аяқталды",
    "errorPasswordResetFailed": "Құпия сөзді қалпына келтіру сәтсіз аяқталды",
    "errorStoreNameRequired": "Дүкен атауын енгізіңіз",
    "adminPanel": "Әкімші панелі",
    "adminSubtitle": "MarketAI маркетплейсті басқару",
    "adminButton": "Әкімші",
    "checkFields": "Өрістерді тексеріңіз",
    "checkFieldsMessage": "Атауын, санатын, нөлден үлкен бағасын және дұрыс қалдығын толтырыңыз.",
    "deleteProductTitle": "Тауарды жою?",
    "deleteProductMessage": "Тауар тізімнен жойылады. Бұл әрекетті болдырмау мүмкін емес.",
    "active": "Белсенді",
    "draft": "Жоба",
    "Активный": "Белсенді",
    "Черновик": "Жоба",
    "Архив": "Мұрағат",
    "archived": "Мұрағат",
    "confirmDelete": "Сіз сенімдісіз бе?",
    "deleteWarning": "Бұл әрекетті болдырмау мzүмкін емес.",
    "revenue": "Табыс",
    "noDataYet": "Шолу",
    "noDataMessage": "Әзірге деректер жоқ. Алғашқы тауарды қосыңыз немесе дүкен статистикасын көру үшін алғашқы тапсырысты күтіңіз.",
    "manageOrders": "Тапсырыстарды басқару",
    "orderDescription": "Тапсырыстарды қарау және өңдеу мәртебесін өзгерту.",
    "orderId": "Тапсырыс",
    "customer": "Клиент",
    "amount": "Сома",
    "orderStatus": "Мәртебе",
    "changeStatus": "Мәртебені өзгерту",
    "statusNew": "Жаңа",
    "statusProcessing": "Өңделуде",
    "statusCompleted": "Аяқталды",
    "statusCancelled": "Бас тартылды",
    "noOrders": "Әзірге тапсырыстар жоқ",
    "manageProducts": "Тауарларды басқару",
    "productsDescription": "Тауарлар, санаттар, бағалар, қалдықтар және жариялау мәртебелері.",
    "productListName": "Атауы",
    "productListCategory": "Санат",
    "productListPrice": "Бағасы",
    "productListStock": "Қалдық",
    "productListStatus": "Мәртебе",
    "actions": "Әрекеттер",
    "noProducts": "Әзірге тауарлар қосылмаған",
    "manageUsers": "Пайдаланушыларды басқару",
    "usersDescription": "Рөлдер, аккаунт мәртебелері және әкімшілік функцияларға қолжетімділік.",
    "userName": "Аты",
    "userEmail": "Email",
    "userRole": "Рөл",
    "userStatus": "Мәртебе",
    "roleAdmin": "Әкімші",
    "roleSeller": "Сатушы",
    "roleUser": "Сатып алушы",
    "statusActive": "Белсенді",
    "statusBlocked": "Бұғатталған",
    "noUsers": "Әзірге пайдаланушылар жоқ",
    "sellersMarketAI": "MarketAI сатушыларға",
    "sellerLoginTitle": "Сатушы кабинетіне кіру",
    "sellerLoginDesc": "MarketAI панелінде витринаны, тауар карточкаларын және тапсырыстарды басқаруды жалғастырыңыз.",
    "benefits": "Витринаны басқару,Қалдықтарды жаңарту,Тапсырыстар дашборды",
    "resetPassword": "Құпия сөзді қалпына келтіру",
    "resetEmailStep": "Қалпына келтіру кодын алу үшін аккаунт электрондық поштасын енгізіңіз.",
    "resetCodeStep": "Хаттан 6 цифрды енгізіңіз.",
    "resetPasswordStep": "Жаңа құпия сөз ойлап табыңыз.",
    "emailPlaceholder": "seller@example.com",
    "codePlaceholder": "000000",
    "sendEmail": "Хат жіберу",
    "confirmCode": "Кодты растау",
    "saveNewPassword": "Құпия сөзді сақтау",
    "backToLogin": "Кіруге оралу",
    "loginButton": "Кіру",
    "noAccountYet": "Әлі сатушы аккаунтыңыз жоқ па?",
    "createAccount": "Құру",
    "forgotPassword": "Құпия сөзді ұмыттыңыз ба?",
    "createSellerAccount": "Сатушы аккаунтын құру",
    "registerDesc": "Тауарларды дайындау, тапсырыстарды басқару және маркетплейс дашбордын ашу үшін дүкеніңізді тіркеңіз.",
    "registerBenefits": "Витринаны баптау,Тауар карточкалары,Орындалудағы тапсырыстар",
    "storeName": "Дүкен атауы",
    "passwordConfirmation": "Құпия сөзді растау",
    "acceptAgreement": "Мен пайдаланушы келісімін қабылдаймын",
    "registerButton": "Сатушы аккаунтын құру",
    "alreadyHaveAccount": "MarketAI-де сатып жатырсыз ба?",
    "loginLink": "Кіру",
    "emailConfirmation": "Электрондық поштаны растау",
    "codeSentTo": "Мына мекенжайға жіберілген растау кодын енгізіңіз",
    "verificationCode": "Растау коды",
    "resendCode": "Кодты қайта жіберу",
    "changeRegistrationData": "Тіркеу деректерін өзгерту",
    "sellerCabinet": "MarketAI сатушы кабинеті",
    "welcomeTitle": "Сатылымды бастаңыз және дүкенді бір жерде басқарыңыз",
    "welcomeDesc": "Сатушыларға арналған кеңістік: каталог, тапсырыстар, пайдаланушылар және дүкен жағдайының жылдам шолуы, әр түрлі құралдар арасында ауысусыз.",
    "createStore": "Дүкен құру",
    "loginCabinet": "Кабинетке кіру",
    "workplace": "Жұмыс панелі",
    "metricsProducts": "Тауарлар",
    "metricsOrders": "Тапсырыстар",
    "metricsRevenue": "Табыс",
    "statusOrdersProcessing": "тапсырыс өңделуде",
    "statusStockUpdate": "тауар қалдықтарды жаңартуды қажет етеді",
    "statusReadyToPublish": "карточка жариялауға дайын",
    "highlightStoreControl": "Витрина бақылауда",
    "highlightStoreText": "Тауарларды, мәртебелер мен қалдықтарды бір жұмыс кеңістігінде басқарыңыз.",
    "highlightOrders": "Тапсырыстар қиындықсыз",
    "highlightOrdersText": "Сұраныстарды бақылаңыз, мәртебелерді өзгертіңіз және операцияны жақын ұстаңыз.",
    "highlightPulse": "Дүкен пульсі",
    "highlightPulseText": "Табысты, белсенділікті және негізгі көрсеткіштерді артық шусыз көріңіз.",
    "agreementTitle": "Пайдаланушы келісімі",
    "agreementDesc": "MarketAI панелін пайдаланатын сатушыларға арналған шарттар. Бұл келісімнің frontend нұсқасы, кейін backend ережелерімен кеңейтілуі мүмкін.",
    "sectionGeneral": "1. Жалпы шарттар",
    "sectionGeneralText": "Келісім MarketAI сатушы кабинетін пайдаланудың негізгі ережелерін сипаттайды, оның ішінде витринаны баптау, тауарларды басқару және тапсырыстарды өңдеу.",
    "sectionAccount": "2. Сатушы аккаунты",
    "sectionAccountText": "Сатушы аккаунт деректерінің, дүкен ақпаратының, тауар сипаттамаларының, бағалардың және тапсырыстарды өңдеу ақпаратының дұрыстығына жауапты.",
    "sectionProducts": "3. Тауарлар туралы ақпарат",
    "sectionProductsText": "Тауар карточкаларында дұрыс атаулар, санаттар, бағалар, қалдықтар және мәртебелер болуы керек. Демодеректерді backend қызметтері қосылғаннан кейін ауыстыруға болады.",
    "sectionAdmin": "4. Әкімшілендіру құралдары",
    "sectionAdminText": "Панель маркетплейс операциялары үшін интерфейстік құралдарды ұсынады. Бизнес ережелер, модерация, төлемдер және жеткізу кейін кеңейтілуі мүмкін.",
    "sectionUpdates": "5. Жаңартулар",
    "sectionUpdatesText": "MarketAI сатушы өнімі дамыған сайын, backend қызметтері қосылған сайын және жаңа операциялық функциялар пайда болған сайын шарттарды жаңарта алады.",
    "sellerWorkplace": "Витрина, каталог және тапсырыстарды басқару үшін сатушы жұмыс кеңістігі.",
    "sellerNavigation": "Навигация",
    "sellerContacts": "Байланыс",
    "sellerSettings": "Баптаулар",
    "sellerTheme": "Тақырып",
    "sellerLanguage": "Тіл",
    "sellerFooterCopyright": "© 2026 MarketAI",
    "sellerFooterTagline": "Маркетплейсті басқаруға арналған сатушы құралдары",
    "settingsEyebrow": "Дүкен баптаулары",
    "settingsTitle": "Профиль, қолжетімділік және қауіпсіздік",
    "settingsDescription": "Дүкен деректерін, заңды ақпаратты, команда рөлдерін және маңызды әрекеттерді басқарыңыз.",
    "settingsSave": "Сақтау",
    "settingsSaved": "Баптаулар жергілікті түрде сақталды.",
    "settingsStore": "Дүкен",
    "settingsStoreDescription": "Сатып алушылар сатушыны тануы үшін обложка, атау, сипаттама және байланыстар.",
    "settingsCover": "Обложка",
    "settingsCoverHint": "Обложка суретін қолмен жүктеңіз",
    "settingsCoverUpload": "Обложка қосу",
    "settingsStoreName": "Дүкен атауы",
    "settingsStoreNamePlaceholder": "Дүкен атауы",
    "settingsStoreDescriptionField": "Сипаттама",
    "settingsStoreDescriptionPlaceholder": "Дүкен не сататынын және сатып алушыларға несімен пайдалы екенін жазыңыз.",
    "settingsCity": "Қала",
    "settingsCityPlaceholder": "Екатеринбург",
    "settingsPhone": "Телефон",
    "settingsEmail": "Пошта",
    "settingsLegal": "Заңды деректер",
    "settingsLegalDescription": "Сатушыны тексеру, құжаттар және төлемдер үшін деректер.",
    "settingsLegalSave": "Заңды деректерді сақтау",
    "settingsLegalSubmit": "Тексеруге жіберу",
    "settingsLegalSaved": "Заңды деректер сақталды.",
    "settingsLegalSubmitted": "Заңды деректер тексеруге жіберілді.",
    "settingsBusinessType": "Сатушы түрі",
    "settingsBusinessIndividual": "ЖК",
    "settingsBusinessCompany": "Компания",
    "settingsBusinessSelfEmployed": "Өзін-өзі жұмыспен қамтыған",
    "settingsTaxId": "ИИН / БИН",
    "settingsLegalName": "Заңды атауы",
    "settingsLegalNamePlaceholder": "ЖК MarketAI Store",
    "settingsLegalAddress": "Заңды мекенжай",
    "settingsLegalAddressPlaceholder": "Қала, көше, үй",
    "settingsBankName": "Банк",
    "settingsBankNamePlaceholder": "Банк атауы",
    "settingsIban": "IBAN / шот",
    "settingsTeam": "Команда және қолжетімділік",
    "settingsTeamDescription": "Қызметкерлерді шақырып, тапсырыс, тауар және аналитика үшін рөлдер беріңіз.",
    "settingsTeamLocked": "Команда және қолжетімділік дүкен белсендірілгеннен кейін ашылады.",
    "settingsTeamEmailPlaceholder": "қызметкер email",
    "settingsInvite": "Шақыру",
    "settingsInviteTitle": "Қатысушыны шақыру",
    "settingsInviteDescription": "Қызметкер деректерін толтырып, қолжетімділік рөлін таңдаңыз.",
    "settingsInviteSubmit": "Шақыру жіберу",
    "settingsMemberName": "Аты",
    "settingsMemberNamePlaceholder": "Қызметкер аты",
    "settingsRole": "Рөл",
    "settingsRoleOwner": "Иесі",
    "settingsRoleManager": "Менеджер",
    "settingsRoleOperator": "Тапсырыс операторы",
    "settingsRoleViewer": "Көру",
    "settingsTeamActive": "Белсенді",
    "settingsTeamInvited": "Шақырылды",
    "settingsDanger": "Қауіпті аймақ",
    "settingsDangerDescription": "Дүкен қолжетімділігі мен сатушы деректеріне әсер ететін әрекеттер.",
    "settingsDeactivateTitle": "Дүкенді кідірту",
    "settingsDeactivateDescription": "Сатып алушылар уақытша жаңа тапсырыс рәсімдей алмайды.",
    "settingsDeactivate": "Кідірту",
    "settingsDeactivateDialog": "Бұл әрекет әзірге frontend сценарийі ретінде дайындалды. Backend қосылғаннан кейін дүкен мәртебесін өзгертеді.",
    "settingsDeleteTitle": "Дүкенді жою",
    "settingsDeleteDescription": "Дүкенді жою қосымша растауды және иесінің құқықтарын тексеруді талап етеді.",
    "settingsDelete": "Дүкенді жою",
    "settingsDeleteDialog": "Backend растауынсыз дүкенді жою әзірге орындалмайды. Әрекет интерфейстегі қорғалған нүкте ретінде қалдырылды.",
    "sellerStatusPendingLegal": "Дүкенді тексеруге жіберу үшін заңды деректерді толтырыңыз.",
    "sellerStatusUnderReview": "Тексерілуде",
    "sellerStatusRejected": "Заңды деректерді түзету керек",
    "sellerStatusSuspended": "Дүкен бұғатталған",
    "moderationMenu": "Модерация",
    "moderationTitle": "Сатушыларды модерациялау",
    "moderationDescription": "Сатушылардың заңды деректерін тексеріп, өтінімдерді мақұлдаңыз немесе қабылдамаңыз.",
    "moderationKey": "Модерация кілті",
    "moderationKeyRequired": "MODERATION_ADMIN_KEY енгізіңіз.",
    "moderationLoad": "Өтінімдерді жүктеу",
    "moderationRefresh": "Жаңарту",
    "moderationLoadFailed": "Өтінімдерді жүктеу мүмкін болмады.",
    "moderationActionFailed": "Әрекетті орындау мүмкін болмады.",
    "moderationEmpty": "Тексеруге өтінімдер жоқ.",
    "moderationApprove": "Мақұлдау",
    "moderationReject": "Қабылдамау",
    "moderationApproved": "Мақұлданды:",
    "moderationRejected": "Қабылданбады:",
    "moderationSubmittedAt": "Жіберілді",
    "moderationRejectTitle": "Өтінімді қабылдамау",
    "moderationRejectComment": "Сатушыға комментарий",
    "moderationRejectPlaceholder": "Мысалы: ИИН/БИН және заңды мекенжайды түзетіңіз",
    "moderationRejectCommentRequired": "Қабылдамау себебі бар комментарий қосыңыз.",
  },
};

// Тип для автокомплита ключей в IDE (берем за основу русский словарь)
export type TranslationKey = keyof typeof translations.ru;

// Ленивая загрузка начального языка (чтобы не было моргания интерфейса)
const getInitialLanguage = (): Lang => {
  const saved = localStorage.getItem('admin-language');
  if (saved === 'ru' || saved === 'en' || saved === 'kk') return saved;

  // Если языка нет в памяти, определяем язык браузера
  const browserLang = navigator.language.slice(0, 2);
  if (browserLang === 'ru' || browserLang === 'en' || browserLang === 'kk') {
    return browserLang as Lang;
  }
  
  return 'ru'; // Фолбэк на русский
};

export function useLanguage() {
  const [lang, setLang] = useState<Lang>(getInitialLanguage);

  useEffect(() => {
    // Гарантируем, что первично выбранный язык записан в localStorage
    localStorage.setItem('admin-language', lang);
  }, []);

  useEffect(() => {
    const handleStorage = (e: StorageEvent) => {
      if (e.key === 'admin-language') {
        const newLang = e.newValue as Lang;
        if (newLang === 'ru' || newLang === 'en' || newLang === 'kk') setLang(newLang);
      }
    };
    const handleCustom = () => {
      const saved = localStorage.getItem('admin-language') as Lang;
      if (saved === 'ru' || saved === 'en' || saved === 'kk') setLang(saved);
    };
    window.addEventListener('storage', handleStorage);
    window.addEventListener('admin-language-change', handleCustom);
    return () => {
      window.removeEventListener('storage', handleStorage);
      window.removeEventListener('admin-language-change', handleCustom);
    };
  }, []);

  const changeLanguage = useCallback((newLang: string) => {
    if (newLang === 'ru' || newLang === 'en' || newLang === 'kk') {
      localStorage.setItem('admin-language', newLang);
      window.dispatchEvent(new Event('admin-language-change'));
    }
  }, []);

  const t = useCallback((key: TranslationKey | (string & {})): string => {
    const selected = translations[lang];
    return selected?.[key] ?? key;
  }, [lang]);

  return { lang, changeLanguage, t };
}
