import { ValidationPipe } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import {
  DocumentBuilder,
  type OpenAPIObject,
  SwaggerModule,
} from '@nestjs/swagger';
import { AppModule } from './app.module';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
    }),
  );

  const swaggerConfig = new DocumentBuilder()
    .setTitle('MarketAI AI Agent Service')
    .setDescription(
      [
        'AI assistant API for product recommendations and persisted chat history.',
        '',
        'Conversation state is stored by session. Anonymous users are identified by x-guest-id, authenticated users can be forwarded as x-user-id by the API Gateway.',
      ].join('\n'),
    )
    .setVersion('1.0')
    .addServer('http://127.0.0.1:4006', 'Local development')
    .addServer('http://localhost:4006', 'Local development (localhost)')
    .addTag('AI chat', 'Assistant message exchange and product recommendations')
    .addTag('AI chat history', 'Persisted assistant sessions and messages')
    .addApiKey(
      {
        type: 'apiKey',
        in: 'header',
        name: 'x-guest-id',
        description: 'Anonymous browser chat id generated by the client',
      },
      'guestId',
    )
    .build();

  const swaggerDocument = SwaggerModule.createDocument(app, swaggerConfig);
  groupAiSwaggerTags(swaggerDocument);

  SwaggerModule.setup('docs', app, swaggerDocument, {
    customSiteTitle: 'MarketAI AI Agent API',
    swaggerOptions: {
      docExpansion: 'none',
      filter: true,
      persistAuthorization: true,
      displayRequestDuration: true,
      tagsSorter: 'alpha',
      operationsSorter: 'method',
    },
  });

  await app.listen(process.env.AI_AGENT_PORT ?? process.env.PORT ?? 4006);
}

function groupAiSwaggerTags(document: OpenAPIObject) {
  const tagDescriptions = new Map(
    (document.tags ?? []).map((tag) => [tag.name, tag.description]),
  );

  for (const [path, pathItem] of Object.entries(document.paths)) {
    for (const operation of Object.values(pathItem ?? {})) {
      if (!operation || typeof operation !== 'object' || !('tags' in operation)) {
        continue;
      }

      operation.tags = [path.includes('/sessions') ? 'AI chat history' : 'AI chat'];
    }
  }

  document.tags = ['AI chat', 'AI chat history'].map((name) => ({
    name,
    description: tagDescriptions.get(name),
  }));
}

void bootstrap();
